### ISSUE TITLE
Etablissements localisés à Null Island

### ISSUE THREAD

**Issue by pyrog** [etalab/annuaire-entreprises.data.gouv.fr#1]
Un exemple parmi d'autres.

L'établissement [356 000 000 69759](https://annuaire-entreprises.data.gouv.fr/entreprise/35600000069759) de La Poste est [localisé aux coordonnées 0,0](https://annuaire-entreprises.data.gouv.fr/rechercher/carte?siret=35600000069759).
Adresse : 92350 LE PLESSIS-ROBINSON

**Comment by XavierJp** [comment]
Bonjour @pyrog 

Merci de nous avoir fait remonter ce problème. Pour information la structure des pages a changé, et la nouvelle page établissement est : 
https://annuaire-entreprises.data.gouv.fr/etablissement/35600000069759

Cet établissement est une création récente (26/09/2020) et j'ai l'impression que le problème a depuis été réglé par la mise a jour de la base SIRENE (qui a lieu chaque premier du mois)

@geoffreyaldebert qu'en penses tu ?
