### ISSUE TITLE
Recherche par enseigne impossible

### ISSUE THREAD

**Issue by pyrog** [etalab/annuaire-entreprises.data.gouv.fr#6]
Par exemple "[Alice Délice](https://annuaire-entreprises.data.gouv.fr/rechercher?terme=Alice+Délice)" ne trouve pas [44213327800360](https://annuaire-entreprises.data.gouv.fr/etablissement/44213327800360).

Cf. #4

**Comment by XavierJp** [comment]
Merci pour votre suggestion, ce serait une belle amélioration effectivement

**Comment by geoffreyaldebert** [comment]
Bonjour, la possibilité de rechercher par enseigne est désormais possible. Nous trouvons maintenant bien l'enseigne ```Alice Délice``` via la recherche (entreprise Kitchen academy).

Je clos l'issue, n'hésitez pas à la rouvrir si vous constater un problème quelconque.

Geoffrey
